-- MySQL Script generated by MySQL Workbench
-- Wed Jun  4 20:31:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clinica_medica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clinica_medica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinica_medica` DEFAULT CHARACTER SET utf8 ;
USE `clinica_medica` ;

-- -----------------------------------------------------
-- Table `clinica_medica`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica_medica`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `clinica_medica`.`pessoa` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `estado_civil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_medica`.`paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica_medica`.`paciente` ;

CREATE TABLE IF NOT EXISTS `clinica_medica`.`paciente` (
  `id_paciente` INT NOT NULL AUTO_INCREMENT,
  `patologia` VARCHAR(45) NULL,
  `comorbidade` VARCHAR(45) NULL,
  `id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_paciente`, `id_pessoa`),
  INDEX `fk_paciente_pessoa1_idx` (`id_pessoa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_medica`.`medico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica_medica`.`medico` ;

CREATE TABLE IF NOT EXISTS `clinica_medica`.`medico` (
  `id_medico` INT NOT NULL AUTO_INCREMENT,
  `crm` INT NOT NULL,
  `especialidade` VARCHAR(45) NOT NULL,
  `id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_medico`, `id_pessoa`),
  UNIQUE INDEX `crm_UNIQUE` (`crm` ASC) VISIBLE,
  INDEX `fk_medico_pessoa_idx` (`id_pessoa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_medica`.`consulta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica_medica`.`consulta` ;

CREATE TABLE IF NOT EXISTS `clinica_medica`.`consulta` (
  `id_consulta` INT NOT NULL AUTO_INCREMENT,
  `data_consulta` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `observacoes` TEXT NULL,
  `id_pessoa` INT NOT NULL,
  `id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_consulta`, `id_pessoa`),
  INDEX `fk_consulta_medico2_idx` (`id_pessoa` ASC) VISIBLE,
  INDEX `fk_consulta_paciente1_idx` (`id_paciente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_medica`.`exames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica_medica`.`exames` ;

CREATE TABLE IF NOT EXISTS `clinica_medica`.`exames` (
  `id_exame` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  `resultado` VARCHAR(45) NOT NULL,
  `id_consulta` INT NOT NULL,
  PRIMARY KEY (`id_exame`),
  INDEX `fk_exames_consulta1_idx` (`id_consulta` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
